os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -r ci-requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - flake8 --ignore=D,W503,W504,F403,F405 examples/
  - flake8 MRCpy/ tests/
  - travis_wait coverage run --source=MRCpy/ -m unittest discover -s tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_PAGES_TOKEN
    keep_history: true
    repo: MachineLearningBCAM/MRCpy.github.io
    target_branch: gh-pages
    on:
      # Which branch on commit/push will trigger deployment
      branch: master
    fqdn: MRCpy.github.io
    project_name: MRCpy
    local_dir: public
    email: bkartheekreddy@gmail.com
    name: Kartheek Bondugula